a = []

##################################################################
a.append(["land-of-wind", "phantom-figurine", "1, 2"])
a.append(["land-of-wind", "elf-archer", "1, 2, 7"])
a.append(["land-of-wind", "slime", "1, 2"])
a.append(["land-of-wind", "bat", "1, 2, 5, 6, 8"])
a.append(["land-of-wind", "little-skeleton", "1, 2, 3, 4, 9"])
a.append(["land-of-wind", "tree-guard", "3, 4, 8"])
a.append(["land-of-wind", "statue", "3, 4, 9"])
a.append(["land-of-wind", "skeleton-archer", "3, 4, 9"])
a.append(["land-of-wind", "goblin-assassin", "3, 4"])
a.append(["land-of-wind", "wolf-cavalry-a", "5, 6, 7"])
a.append(["land-of-wind", "orc-flamen", "5, 6"])
a.append(["land-of-wind", "duel-axe-orc", "5, 6"])
a.append(["land-of-wind", "wolf-orc", "5, 6"])
a.append(["land-of-wind", "zombie", "7"])
a.append(["land-of-wind", "wolf-cavalry-b", "7"])
a.append(["land-of-wind", "deer-spirit", "7"])
a.append(["land-of-wind", "skeleton-mage", "8"])
a.append(["land-of-wind", "cyclops", "8"])
a.append(["land-of-wind", "ghost-mage", "8"])
a.append(["land-of-wind", "succubus-oni", "9"])
a.append(["land-of-wind", "fire-statue", "9"])
a.append(["land-of-wind", "spar-giant", "10"])
a.append(["land-of-summer", "bat", "1, 2, 4"])
a.append(["land-of-summer", "statue", "1, 2"])
a.append(["land-of-summer", "slime", "1"])
a.append(["land-of-summer", "water-element", "1, 2"])
a.append(["land-of-summer", "elf-archer", "1, 7, 8"])
a.append(["land-of-summer", "wolf-cavalry-a", "2"])
a.append(["land-of-summer", "wolf-cavalry-b", "2"])
a.append(["land-of-summer", "cyclops", "3, 4"])
a.append(["land-of-summer", "claw-beast", "3"])
a.append(["land-of-summer", "fire-beast", "3"])
a.append(["land-of-summer", "fire-spirit", "3, 4"])
a.append(["land-of-summer", "fire-element", "3, 4"])
a.append(["land-of-summer", "fire-statue", "4"])
a.append(["land-of-summer", "skeleton-mage", "5, 6"])
a.append(["land-of-summer", "zombie", "5, 6"])
a.append(["land-of-summer", "skeleton-archer", "5, 6"])
a.append(["land-of-summer", "ghost-mage", "5, 6"])
a.append(["land-of-summer", "sword-ghost", "5, 6"])
a.append(["land-of-summer", "dark-knight", "5, 6"])
a.append(["land-of-summer", "flower-elf", "7, 8"])
a.append(["land-of-summer", "tree-elder", "7, 8"])
a.append(["land-of-summer", "deer-spirit", "7, 8"])
a.append(["land-of-summer", "light", "7, 8"])
a.append(["land-of-summer", "duel-axe-orc", "9"])
a.append(["land-of-summer", "dog-headed-orc", "9"])
a.append(["land-of-summer", "wolf-orc", "9"])
a.append(["land-of-summer", "tree-guard", "9"])
a.append(["land-of-summer", "orc-flamen", "9"])
a.append(["land-of-forest", "bat", "1, 2, 5"])
a.append(["land-of-forest", "goblin-assassin", "1, 2"])
a.append(["land-of-forest", "duel-axe-orc", "1, 2"])
a.append(["land-of-forest", "slime", "1"])
a.append(["land-of-forest", "cyclops", "1"])
a.append(["land-of-forest", "phantom-figurine", "2, 6"])
a.append(["land-of-forest", "wolf-cavalry-b", "2"])
a.append(["land-of-forest", "claw-beast", "3, 4"])
a.append(["land-of-forest", "succubus-oni", "3, 4"])
a.append(["land-of-forest", "fire-spirit", "3, 4"])
a.append(["land-of-forest", "fire-beast", "3, 4"])
a.append(["land-of-forest", "demon-lord", "3"])
a.append(["land-of-forest", "fire-element", "4"])
a.append(["land-of-forest", "elf-archer", "5, 7"])
a.append(["land-of-forest", "flower-elf", "5"])
a.append(["land-of-forest", "tree-guard", "5"])
a.append(["land-of-forest", "light", "5"])
a.append(["land-of-forest", "dog-headed-orc", "6"])
a.append(["land-of-forest", "wolf-orc", "6"])
a.append(["land-of-forest", "ghost", "6, 8, 9"])
a.append(["land-of-forest", "moonlight-flamen", "6"])
a.append(["land-of-forest", "skeleton-archer", "7"])
a.append(["land-of-forest", "statue", "7"])
a.append(["land-of-forest", "fire-statue", "7"])
a.append(["land-of-forest", "little-skeleton", "7"])
a.append(["land-of-forest", "ghost-mage", "8, 9"])
a.append(["land-of-forest", "skeleton-mage", "8, 9"])
a.append(["land-of-forest", "butcher-zombie", "8, 9"])
a.append(["land-of-forest", "zombie", "8, 9"])
a.append(["land-of-chaos", "sickle-ghost", "23, 25"])
a.append(["land-of-chaos", "little-skeleton", "28, 35, 47, 50, 52, 1, 23, 25"])
a.append(["land-of-chaos", "zombie", "28, 26"])
a.append(["land-of-chaos", "fire-element", "29, 31"])
a.append(["land-of-chaos", "water-element", "29, 31"])
a.append(["land-of-chaos", "wind-knight", "32, 34"])
a.append(["land-of-chaos", "succubus", "32, 34"])
a.append(["land-of-chaos", "ghost-mage", "35, 22"])
a.append(["land-of-chaos", "dark-knight", "37, 20"])
a.append(["land-of-chaos", "butcher-zombie", "37, 26, 28"])
a.append(["land-of-chaos", "tree-guard", "38, 40, 14, 16"])
a.append(["land-of-chaos", "fire-statue", "40, 5"])
a.append(["land-of-chaos", "elf-archer", "41"])
a.append(["land-of-chaos", "cyclops", "41, 43, 17, 19"])
a.append(["land-of-chaos", "deer-spirit", "43, 13"])
a.append(["land-of-chaos", "goblin-assassin", "44, 46"])
a.append(["land-of-chaos", "goblin-thief", "44, 46, 53, 2, 4"])
a.append(["land-of-chaos", "slime", "47, 1"])
a.append(["land-of-chaos", "phantom-figurine", "49, 50, 52, 1"])
a.append(["land-of-chaos", "skeleton-archer", "49, 1"])
a.append(["land-of-chaos", "duel-axe-orc", "53, 2"])
a.append(["land-of-chaos", "wolf-cavalry-b", "2"])
a.append(["land-of-chaos", "wolf-cavalry-a", "2, 4"])
a.append(["land-of-chaos", "armored-golem", "5, 7"])
a.append(["land-of-chaos", "gold-golem", "7"])
a.append(["land-of-chaos", "fire-beast", "8"])
a.append(["land-of-chaos", "demon-lord", "8"])
a.append(["land-of-chaos", "fire-spirit", "10"])
a.append(["land-of-chaos", "succubus-oni", "10"])
a.append(["land-of-chaos", "elf-mage", "11"])
a.append(["land-of-chaos", "light", "11, 13"])
a.append(["land-of-chaos", "half-goat", "14, 16"])
a.append(["land-of-chaos", "bat", "17, 19"])
a.append(["land-of-chaos", "ghost", "20, 22"])
a.append(["land-of-chaos", "skeleton-mage", "23"])
a.append(["land-of-chaos", "lich", "32"])
a.append(["land-of-ice", "snake", "1, 3, 5, 7, 9"])
a.append(["land-of-ice", "statue", "1"])
a.append(["land-of-ice", "wind-knight", "1, 2, 5, 8"])
a.append(["land-of-ice", "phantom-figurine", "1, 6"])
a.append(["land-of-ice", "gold-golem", "1"])
a.append(["land-of-ice", "wolf-cavalry-a", "2"])
a.append(["land-of-ice", "little-skeleton", "2, 4, 8, 9"])
a.append(["land-of-ice", "elf-archer", "2"])
a.append(["land-of-ice", "wolf-cavalry-b", "2"])
a.append(["land-of-ice", "armored-golem", "3"])
a.append(["land-of-ice", "succubus", "3, 4, 5, 8"])
a.append(["land-of-ice", "duel-axe-orc", "3"])
a.append(["land-of-ice", "longaxe-orc", "3"])
a.append(["land-of-ice", "dark-knight", "4"])
a.append(["land-of-ice", "ghost", "4"])
a.append(["land-of-ice", "ghost-mage", "4"])
a.append(["land-of-ice", "small-eyed", "5, 8"])
a.append(["land-of-ice", "tree-guard", "5"])
a.append(["land-of-ice", "fire-statue", "6"])
a.append(["land-of-ice", "bat", "6"])
a.append(["land-of-ice", "lich", "6, 8"])
a.append(["land-of-ice", "skeleton-archer", "6, 9"])
a.append(["land-of-ice", "fire-element", "7"])
a.append(["land-of-ice", "sword-ghost", "7"])
a.append(["land-of-ice", "skeleton-mage", "7"])
a.append(["land-of-ice", "water-element", "7"])
a.append(["land-of-ice", "zombie", "9"])
a.append(["land-of-ice", "butcher-zombie", "9"])
a.append(["land-of-ice", "gorgon", "10"])
##################################################################

for b in a:
    slug = b[1]
    land = b[0]
    floor = b[2]
    note = f'Spawns on Floor {floor}'
    if land == "land-of-chaos":
        note = f'May appear on Floor {floor}'
    elf = json_data["elves"].get(slug, {})
    elf["continents"] = elf.get("continents", [])
    for c in elf["continents"]:
        if c["id"] == land:
            c["note"] = note
            break
    else:
        elf["continents"].append({
            "id": land,
            "note": note,
        })

# print(json_data["elves"])
# print(elves)